@path = http://localhost:5001/auth/api/v1/auth

### POST login
POST  {{path}}/login
Content-Type: application/json

{
  "username": "user1",
  "password": "root"
}

### POST register
POST {{path}}/register
Content-Type: application/json

{
  "username": "Pasha3",
  "password": "root",
  "passwordConfirmation": "root"
}