package ru.ci_trainee.authms.service;

import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.ci_trainee.authms.exception.exception.PasswordsDoNotMatchException;
import ru.ci_trainee.authms.exception.exception.RoleNotFoundException;
import ru.ci_trainee.authms.exception.exception.UserNotFoundException;
import ru.ci_trainee.authms.model.User;
import ru.ci_trainee.authms.repository.RoleRepository;
import ru.ci_trainee.authms.repository.UserRepository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class UserService {
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;

    public List<User> getUsers() {
        return userRepository.findAll();
    }

    public User getUser(String username) {
        return userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException("User not found"));
    }

    public User getUser(UUID id) {
        return userRepository.findById(id)
                .orElseThrow(() -> new UserNotFoundException("User not found"));
    }

    @Transactional
    public User create(User user, String passwordConfirmation) {
        if (!user.getPassword().equals(passwordConfirmation)) throw new PasswordsDoNotMatchException();
        if(user.getId() != null) throw new IllegalArgumentException("Id must be generated by server");

        var userRole = roleRepository.findByName("ROLE_USER").orElseThrow(RoleNotFoundException::new);
        user.setRoles(Set.of(userRole));
        user.setIsActive(true);
        user.setPassword(passwordEncoder.encode(user.getPassword()));

        return userRepository.save(user);
    }

    @Transactional
    public void updateLastLogin(UUID userId){
        var user = getUser(userId);
        user.setLastLogin(LocalDateTime.now());
        userRepository.save(user);
    }

    @Transactional
    public void makeAdmin(UUID userId) {
        var user = getUser(userId);
        var adminRole = roleRepository.findByName("ROLE_ADMIN").orElseThrow(RoleNotFoundException::new);

        user.getRoles().add(adminRole);

        userRepository.save(user);
    }
}
