spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_user_db?currentSchema=auth_user_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_user_dev
