spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_user_db?currentSchema=auth_user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: auth_user