spring:
  application:
    name: event-ms
  cloud:
    config:
      uri: http://localhost:5000
      fail-fast: true
  config:
    import: "configserver:"

  liquibase:
    change-log: db/changelog/db.changelog-master.yml


  datasource:
    url: jdbc:postgresql://localhost:5432/event_db?currentSchema=event
    username: postgres
    password: root

