spring:
  application:
    name: event-ms

  redis:
    host: localhost
    port: 6379
    timeout: 60000
    password: root

  cloud:
    config:
      uri: http://localhost:5000
      fail-fast: true
  config:
    import: "configserver:"

app:
  domain:
    event:
      recommendation:
        lock-at-most-for: PT5M
        lock-at-least-for: PT1M
