spring:
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  port: 4002

minio:
  endpoint: http://${MINIO_HOST}:${MINIO_PORT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}

app:
  domain:
    recommendation:
      place-rate: ${RECOMMENDATION_RATE:0 0 1 * * *}
      event-rate: ${RECOMMENDATION_RATE:0 0 1 * * *}
    city:
      coordinates:
        bottom-left-corner:
          latitude: 47.20000
          longitude: 39.55555
        top-left-corner:
          latitude: 47.30600
          longitude: 39.55555
        bottom-right-corner:
          latitude: 47.20000
          longitude: 39.90500
        top-right-corner:
          latitude: 47.30600
          longitude: 39.90500