spring:
  application:
    name: routes-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

server:
  port: 4003

logging:
  level:
    root: INFO
    ru.ci_trainee: DEBUG

yandex:
  gpt:
    api:
      key: ""