spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/profile_db?currentSchema=profile
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: profile
