spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/profile_db?currentSchema=profile_docker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: profile_docker