spring:
  application:
    name: config-server
  profiles:
    active: vault,git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanyaChetvyrtov/TraineeHelper.git
          search-paths: configurations/{application}
          order: 1
        vault:
          host: localhost
          port: 8200
          scheme: http
          kv-version: 2
          backend: secret
          profile-separator: '/'
          skip-ssl-validation: true
          authentication: TOKEN
          token: myroot
          order: 2

server:
  port: 5000
