name: List changed files
description: |
  Build docker image based on Dockerfile in microservice
  Push it to DockerHub

inputs:
  username:
    description: DockerHub username
    required: true
  token:
    description: DockerHub token
    required: true
  files:
    description: changed services
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --debug

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./services/${{ inputs.files }}
        file: ./services/${{ inputs.files }}/Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ inputs.username }}/${{ inputs.files }}:${{ github.sha }}
          ${{ inputs.username }}/${{ inputs.files }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GRADLE_VERSION=8.4
          JDK_VERSION=21